micronaut:
  application:
    name: homepage
  server:
    http-to-https-redirect: true
  security:
    enabled: true
    redirect:
      enabled: false
  router:
    static-resources:
      default:
        enabled: true
        mapping: /**
        headers:
          cache-control: "no-cache, no-store, must-revalidate"
        paths: classpath:public
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
netty:
  default:
    allocator:
      max-order: 3
