runtime: java17
entrypoint: java -jar homepage-all.jar

automatic_scaling:
  min_instances: 1

inbound_services:
  - warmup

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto